---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
url <- list(
  reuse = "https://www.data.gouv.fr/fr/datasets/r/970aafa0-3778-4d8b-b9d1-de937525e379", 
  datasets = "https://www.data.gouv.fr/fr/datasets/r/f868cca6-8da1-4369-a78d-47463f19a9a3"
  )
library(DT)
```

## Liste des jeux de données les plus réutilisés

```{r echo=FALSE, message=FALSE}
readr::read_csv2(file = url$reuse) %>%
  separate_rows(datasets, sep = ",", convert = FALSE)  %>%
  filter(is.na(datasets) == FALSE) %>%
  group_by(datasets) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  left_join(
    y = readr::read_csv2(file = url$datasets) %>% 
      select(id, title, organization), 
    by = c("datasets" =  "id")
    ) %>%
  slice(1:20)  %>%
  datatable()
```



## Anomalies

### Réutilisations sans jeu de données associé

```{r message=FALSE, echo=FALSE}
url$reuse %>%
  readr::read_csv2() %>%
  filter(is.na(datasets)) %>%
  nrow()
```

### Datasets réutilisés mais non exportés dans le fichier de référence

```{r echo=FALSE, message=FALSE}
readr::read_csv2(file = url$reuse) %>%
  separate_rows(datasets, sep = ",", convert = FALSE)  %>%
  filter(is.na(datasets) == FALSE) %>%
  select(datasets) %>%
  distinct() %>%
  anti_join(
    y = read_csv2(file = url$datasets), 
    by = c("datasets" = "id")
  ) %>%
  glimpse()
```


